name: $(Build.BuildId)
resources:
- repo: self
queue:
  name: Hosted VS2017

variables:
  buildConfiguration: 'Release'
  Parameters.RestoreBuildProjects: ''

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: Domino
    organization: 'dillonad-github'
    projectKey: 'DillonAd_Domino'
    projectName: Domino
    extraProperties: |
     sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)\opencover.xml"

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Test*/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --filter "Category=unit" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(Build.SourcesDirectory)/opencover.xml '

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: DotNetCoreCLI@2
  displayName: Package
  inputs:
    command: pack
    projects: '**/*.csproj'
    arguments: '--version-suffix $(Build.BuildId) --output $(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: DillonAd
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'